import { manageCorporateMap } from '../actions/manageCorporate.action';

const initialState = {
  manageCorporateData: [
    {
      companyId: '1',
      companyName: 'Company 1',
      firstName: 'Adam',
      lastName: 'Murphy',
      emailId: 'test123@test.com',
      mobile: '9825098250',
      registrationDate: '10/12/2018',
      status: 'pending',
      isActive: true,
    },
    {
      companyId: '2',
      companyName: 'Company 2',
      firstName: 'raj',
      lastName: 'purohit',
      emailId: 'test543@test.com',
      mobile: '9825022554',
      registrationDate: '18/12/2019',
      status: 'approved',
      isActive: true,
    },
    {
      companyId: '3',
      companyName: 'Company 3',
      firstName: 'manan',
      lastName: 'raj',
      emailId: 'test985@test.com',
      mobile: '9825097564',
      registrationDate: '19/08/2020',
      status: 'pending',
      isActive: true,
    },
    {
      companyId: '4',
      companyName: 'Company 4',
      firstName: 'pooja',
      lastName: 'patil',
      emailId: 'test482@test.com',
      mobile: '9825074125',
      registrationDate: '23/01/2017',
      status: 'rejected',
      isActive: true,
    },
    {
      companyId: '5',
      companyName: 'Company 5',
      firstName: 'Adam',
      lastName: 'Murphy',
      emailId: 'test123@test.com',
      mobile: '9825098250',
      registrationDate: '10/12/2018',
      status: 'pending',
      isActive: true,
    },
    {
      companyId: '6',
      companyName: 'Company 6',
      firstName: 'raj',
      lastName: 'purohit',
      emailId: 'test543@test.com',
      mobile: '9825022554',
      registrationDate: '18/12/2019',
      status: 'approved',
      isActive: true,
    },
    {
      companyId: '7',
      companyName: 'Company 7',
      firstName: 'manan',
      lastName: 'raj',
      emailId: 'test985@test.com',
      mobile: '9825097564',
      registrationDate: '19/08/2020',
      status: 'pending',
      isActive: true,
    },
    {
      companyId: '8',
      companyName: 'Company 8',
      firstName: 'pooja',
      lastName: 'patil',
      emailId: 'test482@test.com',
      mobile: '9825074125',
      registrationDate: '23/01/2017',
      status: 'rejected',
      isActive: true,
    },
    {
      companyId: '9',
      companyName: 'Company 9',
      firstName: 'Adam',
      lastName: 'Murphy',
      emailId: 'test123@test.com',
      mobile: '9825098250',
      registrationDate: '10/12/2018',
      status: 'pending',
      isActive: true,
    },
    {
      companyId: '10',
      companyName: 'Company 10',
      firstName: 'raj',
      lastName: 'purohit',
      emailId: 'test543@test.com',
      mobile: '9825022554',
      registrationDate: '18/12/2019',
      status: 'approved',
      isActive: true,
    },
    {
      companyId: '11',
      companyName: 'Company 11',
      firstName: 'manan',
      lastName: 'raj',
      emailId: 'test985@test.com',
      mobile: '9825097564',
      registrationDate: '19/08/2020',
      status: 'pending',
      isActive: true,
    },
    {
      companyId: '12',
      companyName: 'Company 12',
      firstName: 'pooja',
      lastName: 'patil',
      emailId: 'test482@test.com',
      mobile: '9825074125',
      registrationDate: '23/01/2017',
      status: 'rejected',
      isActive: true,
    },
    {
      companyId: '13',
      companyName: 'Company 13',
      firstName: 'Adam',
      lastName: 'Murphy',
      emailId: 'test123@test.com',
      mobile: '9825098250',
      registrationDate: '10/12/2018',
      status: 'pending',
      isActive: true,
    },
    {
      companyId: '14',
      companyName: 'Company 14',
      firstName: 'raj',
      lastName: 'purohit',
      emailId: 'test543@test.com',
      mobile: '9825022554',
      registrationDate: '18/12/2019',
      status: 'approved',
      isActive: true,
    },
    {
      companyId: '15',
      companyName: 'Company 15',
      firstName: 'manan',
      lastName: 'raj',
      emailId: 'test985@test.com',
      mobile: '9825097564',
      registrationDate: '19/08/2020',
      status: 'pending',
      isActive: true,
    },
    {
      companyId: '16',
      companyName: 'Company 16',
      firstName: 'pooja',
      lastName: 'patil',
      emailId: 'test482@test.com',
      mobile: '9825074125',
      registrationDate: '23/01/2017',
      status: 'rejected',
      isActive: true,
    },
    {
      companyId: '17',
      companyName: 'Company 17',
      firstName: 'Adam',
      lastName: 'Murphy',
      emailId: 'test123@test.com',
      mobile: '9825098250',
      registrationDate: '10/12/2018',
      status: 'pending',
      isActive: true,
    },
    {
      companyId: '18',
      companyName: 'Company 18',
      firstName: 'raj',
      lastName: 'purohit',
      emailId: 'test543@test.com',
      mobile: '9825022554',
      registrationDate: '18/12/2019',
      status: 'approved',
      isActive: true,
    },
    {
      companyId: '19',
      companyName: 'Company 19',
      firstName: 'manan',
      lastName: 'raj',
      emailId: 'test985@test.com',
      mobile: '9825097564',
      registrationDate: '19/08/2020',
      status: 'pending',
      isActive: true,
    },
    {
      companyId: '20',
      companyName: 'Company 20',
      firstName: 'pooja',
      lastName: 'patil',
      emailId: 'test482@test.com',
      mobile: '9825074125',
      registrationDate: '23/01/2017',
      status: 'rejected',
      isActive: true,
    },
    {
      companyId: '21',
      companyName: 'Company 21',
      firstName: 'Adam',
      lastName: 'Murphy',
      emailId: 'test123@test.com',
      mobile: '9825098250',
      registrationDate: '10/12/2018',
      status: 'pending',
      isActive: true,
    },
    {
      companyId: '22',
      companyName: 'Company 22',
      firstName: 'raj',
      lastName: 'purohit',
      emailId: 'test543@test.com',
      mobile: '9825022554',
      registrationDate: '18/12/2019',
      status: 'approved',
      isActive: true,
    },
    {
      companyId: '23',
      companyName: 'Company 23',
      firstName: 'manan',
      lastName: 'raj',
      emailId: 'test985@test.com',
      mobile: '9825097564',
      registrationDate: '19/08/2020',
      status: 'pending',
      isActive: true,
    },
    {
      companyId: '24',
      companyName: 'Company 24',
      firstName: 'pooja',
      lastName: 'patil',
      emailId: 'test482@test.com',
      mobile: '9825074125',
      registrationDate: '23/01/2017',
      status: 'rejected',
      isActive: true,
    },
  ],
};

const manageCorporateReducer = (state = initialState, action) => {
  switch (action.type) {
    case manageCorporateMap.UPDATE_MANAGE_CORPORATE_STATUS: {
      let tempManageCorporateData = state.manageCorporateData.map((company) => {
        if (company.companyId === action.payload.companyId) {
          return { ...company, status: action.payload.status };
        } else {
          return company;
        }
      });
      return {
        ...state,
        manageCorporateData: tempManageCorporateData,
      };
    }
    case manageCorporateMap.UPDATE_MANAGE_CORPORATE_ISACTIVE: {
      let tempManageCorporateData = state.manageCorporateData.map((company) => {
        if (company.companyId === action.payload.companyId) {
          return { ...company, isActive: action.payload.isActive };
        } else {
          return company;
        }
      });
      return {
        ...state,
        manageCorporateData: tempManageCorporateData,
      };
    }
    default:
      return state;
  }
};

export default manageCorporateReducer;
