import { manageOrderMap } from '../actions/manageOrder.action';

const initialState = {
  manageOrderData: [
    {
      orderId: 1,
      corporateName: 'Corporate 1',
      contactPerson: 'Bobby Gibort',
      newOrder: [
        {
          newOrderId: 1,
          employeeName: 'Mathew Jordon',
          employeeId: 25456,
          allocatedLicenceType: 'silver',
          orderNo: 235,
          orderDate: '30/10/2020',
          orderCost: 325,
          firstThreeMonthCost: 110,
          paymentStatus: 'pending',
          orderConfirm: false,
          orderConfirmDate: '',
          dispatchStatus: false,
          dispatchDate: '',
          deliveryDate: '',
          employeeOrders: [
            {
              employeeOrderId: 1,
              itemName: 'laptop',
              itemId: 321,
              itemCost: 325,
              firstThreeMonthCost: 100,
            },
            {
              employeeOrderId: 2,
              itemName: 'Keyboard',
              itemId: 520,
              itemCost: 600,
              firstThreeMonthCost: 200,
            },
            {
              employeeOrderId: 3,
              itemName: 'Mouse',
              itemId: 211,
              itemCost: 125,
              firstThreeMonthCost: 40,
            },
          ],
        },
        {
          newOrderId: 2,
          employeeName: 'Sara Jordon',
          employeeId: 25456,
          allocatedLicenceType: 'Gold',
          orderNo: 235,
          orderDate: '30/10/2020',
          orderCost: 325,
          firstThreeMonthCost: 110,
          paymentStatus: 'pending',
          orderConfirm: false,
          orderConfirmDate: '',
          dispatchStatus: false,
          dispatchDate: '',
          deliveryDate: '',
          employeeOrders: [
            {
              employeeOrderId: 1,
              itemName: 'laptop',
              itemId: 321,
              itemCost: 325,
              firstThreeMonthCost: 100,
            },
            {
              employeeOrderId: 2,
              itemName: 'Keyboard',
              itemId: 520,
              itemCost: 600,
              firstThreeMonthCost: 200,
            },
            {
              employeeOrderId: 3,
              itemName: 'Mouse',
              itemId: 211,
              itemCost: 125,
              firstThreeMonthCost: 40,
            },
          ],
        },
        {
          newOrderId: 3,
          employeeName: 'Greg wilson',
          employeeId: 25456,
          allocatedLicenceType: 'platinum',
          orderNo: 235,
          orderDate: '30/10/2020',
          orderCost: 325,
          firstThreeMonthCost: 110,
          paymentStatus: 'pending',
          orderConfirm: false,
          orderConfirmDate: '',
          dispatchStatus: false,
          dispatchDate: '',
          deliveryDate: '',
          employeeOrders: [
            {
              employeeOrderId: 1,
              itemName: 'laptop',
              itemId: 321,
              itemCost: 325,
              firstThreeMonthCost: 100,
            },
            {
              employeeOrderId: 2,
              itemName: 'Keyboard',
              itemId: 520,
              itemCost: 600,
              firstThreeMonthCost: 200,
            },
            {
              employeeOrderId: 3,
              itemName: 'Mouse',
              itemId: 211,
              itemCost: 125,
              firstThreeMonthCost: 40,
            },
          ],
        },
      ],
      pastOrder: [
        {
          pastOrderId: 1,
          employeeName: 'Mathew Jordon',
          employeeId: 25456,
          allocatedLicenceType: 'silver',
          orderNo: 235,
          orderDate: '30/11/2019',
          orderCost: 325,
          firstThreeMonthCost: 110,
          paymentStatus: 'received',
          orderConfirm: true,
          orderConfirmDate: '30/12/2019',
          dispatchStatus: true,
          dispatchDate: '01/01/2020',
          deliveryDate: '10/01/2020',
          employeeOrders: [
            {
              employeeOrderId: 1,
              itemName: 'laptop',
              itemId: 321,
              itemCost: 325,
              firstThreeMonthCost: 100,
            },
            {
              employeeOrderId: 2,
              itemName: 'Keyboard',
              itemId: 520,
              itemCost: 600,
              firstThreeMonthCost: 200,
            },
            {
              employeeOrderId: 3,
              itemName: 'Mouse',
              itemId: 211,
              itemCost: 125,
              firstThreeMonthCost: 40,
            },
          ],
        },
        {
          pastOrderId: 2,
          employeeName: 'Sara Jordon',
          employeeId: 25456,
          allocatedLicenceType: 'Gold',
          orderNo: 235,
          orderDate: '30/11/2019',
          orderCost: 325,
          firstThreeMonthCost: 110,
          paymentStatus: 'received',
          orderConfirm: true,
          orderConfirmDate: '30/12/2019',
          dispatchStatus: true,
          dispatchDate: '01/01/2020',
          deliveryDate: '10/01/2020',
          employeeOrders: [
            {
              employeeOrderId: 1,
              itemName: 'laptop',
              itemId: 321,
              itemCost: 325,
              firstThreeMonthCost: 100,
            },
            {
              employeeOrderId: 2,
              itemName: 'Keyboard',
              itemId: 520,
              itemCost: 600,
              firstThreeMonthCost: 200,
            },
            {
              employeeOrderId: 3,
              itemName: 'Mouse',
              itemId: 211,
              itemCost: 125,
              firstThreeMonthCost: 40,
            },
          ],
        },
        {
          pastOrderId: 3,
          employeeName: 'Greg wilson',
          employeeId: 25456,
          allocatedLicenceType: 'platinum',
          orderNo: 235,
          orderDate: '30/11/2019',
          orderCost: 325,
          firstThreeMonthCost: 110,
          paymentStatus: 'received',
          orderConfirm: true,
          orderConfirmDate: '30/12/2019',
          dispatchStatus: true,
          dispatchDate: '01/01/2020',
          deliveryDate: '10/01/2020',
          employeeOrders: [
            {
              employeeOrderId: 1,
              itemName: 'laptop',
              itemId: 321,
              itemCost: 325,
              firstThreeMonthCost: 100,
            },
            {
              employeeOrderId: 2,
              itemName: 'Keyboard',
              itemId: 520,
              itemCost: 600,
              firstThreeMonthCost: 200,
            },
            {
              employeeOrderId: 3,
              itemName: 'Mouse',
              itemId: 211,
              itemCost: 125,
              firstThreeMonthCost: 40,
            },
          ],
        },
      ],
    },
    {
      orderId: 2,
      corporateName: 'Corporate 2',
      contactPerson: 'Hanry Dillon',
      newOrder: [
        {
          newOrderId: 1,
          employeeName: 'Mathew Jordon',
          employeeId: 25456,
          allocatedLicenceType: 'silver',
          orderNo: 235,
          orderDate: '30/10/2020',
          orderCost: 325,
          firstThreeMonthCost: 110,
          paymentStatus: 'pending',
          orderConfirm: false,
          orderConfirmDate: '',
          dispatchStatus: false,
          dispatchDate: '',
          deliveryDate: '',
          employeeOrders: [
            {
              employeeOrderId: 1,
              itemName: 'laptop',
              itemId: 321,
              itemCost: 325,
              firstThreeMonthCost: 100,
            },
            {
              employeeOrderId: 2,
              itemName: 'Keyboard',
              itemId: 520,
              itemCost: 600,
              firstThreeMonthCost: 200,
            },
            {
              employeeOrderId: 3,
              itemName: 'Mouse',
              itemId: 211,
              itemCost: 125,
              firstThreeMonthCost: 40,
            },
          ],
        },
        {
          newOrderId: 2,
          employeeName: 'Sara Jordon',
          employeeId: 25456,
          allocatedLicenceType: 'Gold',
          orderNo: 235,
          orderDate: '30/10/2020',
          orderCost: 325,
          firstThreeMonthCost: 110,
          paymentStatus: 'pending',
          orderConfirm: false,
          orderConfirmDate: '',
          dispatchStatus: false,
          dispatchDate: '',
          deliveryDate: '',
          employeeOrders: [
            {
              employeeOrderId: 1,
              itemName: 'laptop',
              itemId: 321,
              itemCost: 325,
              firstThreeMonthCost: 100,
            },
            {
              employeeOrderId: 2,
              itemName: 'Keyboard',
              itemId: 520,
              itemCost: 600,
              firstThreeMonthCost: 200,
            },
            {
              employeeOrderId: 3,
              itemName: 'Mouse',
              itemId: 211,
              itemCost: 125,
              firstThreeMonthCost: 40,
            },
          ],
        },
        {
          newOrderId: 3,
          employeeName: 'Greg wilson',
          employeeId: 25456,
          allocatedLicenceType: 'platinum',
          orderNo: 235,
          orderDate: '30/10/2020',
          orderCost: 325,
          firstThreeMonthCost: 110,
          paymentStatus: 'pending',
          orderConfirm: false,
          orderConfirmDate: '',
          dispatchStatus: false,
          dispatchDate: '',
          deliveryDate: '',
          employeeOrders: [
            {
              employeeOrderId: 1,
              itemName: 'laptop',
              itemId: 321,
              itemCost: 325,
              firstThreeMonthCost: 100,
            },
            {
              employeeOrderId: 2,
              itemName: 'Keyboard',
              itemId: 520,
              itemCost: 600,
              firstThreeMonthCost: 200,
            },
            {
              employeeOrderId: 3,
              itemName: 'Mouse',
              itemId: 211,
              itemCost: 125,
              firstThreeMonthCost: 40,
            },
          ],
        },
      ],
      pastOrder: [
        {
          pastOrderId: 1,
          employeeName: 'Mathew Jordon',
          employeeId: 25456,
          allocatedLicenceType: 'silver',
          orderNo: 235,
          orderDate: '30/11/2019',
          orderCost: 325,
          firstThreeMonthCost: 110,
          paymentStatus: 'received',
          orderConfirm: true,
          orderConfirmDate: '30/12/2019',
          dispatchStatus: true,
          dispatchDate: '01/01/2020',
          deliveryDate: '10/01/2020',
          employeeOrders: [
            {
              employeeOrderId: 1,
              itemName: 'laptop',
              itemId: 321,
              itemCost: 325,
              firstThreeMonthCost: 100,
            },
            {
              employeeOrderId: 2,
              itemName: 'Keyboard',
              itemId: 520,
              itemCost: 600,
              firstThreeMonthCost: 200,
            },
            {
              employeeOrderId: 3,
              itemName: 'Mouse',
              itemId: 211,
              itemCost: 125,
              firstThreeMonthCost: 40,
            },
          ],
        },
        {
          pastOrderId: 2,
          employeeName: 'Sara Jordon',
          employeeId: 25456,
          allocatedLicenceType: 'Gold',
          orderNo: 235,
          orderDate: '30/11/2019',
          orderCost: 325,
          firstThreeMonthCost: 110,
          paymentStatus: 'received',
          orderConfirm: true,
          orderConfirmDate: '30/12/2019',
          dispatchStatus: true,
          dispatchDate: '01/01/2020',
          deliveryDate: '10/01/2020',
          employeeOrders: [
            {
              employeeOrderId: 1,
              itemName: 'laptop',
              itemId: 321,
              itemCost: 325,
              firstThreeMonthCost: 100,
            },
            {
              employeeOrderId: 2,
              itemName: 'Keyboard',
              itemId: 520,
              itemCost: 600,
              firstThreeMonthCost: 200,
            },
            {
              employeeOrderId: 3,
              itemName: 'Mouse',
              itemId: 211,
              itemCost: 125,
              firstThreeMonthCost: 40,
            },
          ],
        },
        {
          pastOrderId: 3,
          employeeName: 'Greg wilson',
          employeeId: 25456,
          allocatedLicenceType: 'platinum',
          orderNo: 235,
          orderDate: '30/11/2019',
          orderCost: 325,
          firstThreeMonthCost: 110,
          paymentStatus: 'received',
          orderConfirm: true,
          orderConfirmDate: '30/12/2019',
          dispatchStatus: true,
          dispatchDate: '01/01/2020',
          deliveryDate: '10/01/2020',
          employeeOrders: [
            {
              employeeOrderId: 1,
              itemName: 'laptop',
              itemId: 321,
              itemCost: 325,
              firstThreeMonthCost: 100,
            },
            {
              employeeOrderId: 2,
              itemName: 'Keyboard',
              itemId: 520,
              itemCost: 600,
              firstThreeMonthCost: 200,
            },
            {
              employeeOrderId: 3,
              itemName: 'Mouse',
              itemId: 211,
              itemCost: 125,
              firstThreeMonthCost: 40,
            },
          ],
        },
      ],
    },
    {
      orderId: 3,
      corporateName: 'Corporate 3',
      contactPerson: 'jony Buffet',
      newOrder: [
        {
          newOrderId: 1,
          employeeName: 'Mathew Jordon',
          employeeId: 25456,
          allocatedLicenceType: 'silver',
          orderNo: 235,
          orderDate: '30/10/2020',
          orderCost: 325,
          firstThreeMonthCost: 110,
          paymentStatus: 'pending',
          orderConfirm: false,
          orderConfirmDate: '',
          dispatchStatus: false,
          dispatchDate: '',
          deliveryDate: '',
          employeeOrders: [
            {
              employeeOrderId: 1,
              itemName: 'laptop',
              itemId: 321,
              itemCost: 325,
              firstThreeMonthCost: 100,
            },
            {
              employeeOrderId: 2,
              itemName: 'Keyboard',
              itemId: 520,
              itemCost: 600,
              firstThreeMonthCost: 200,
            },
            {
              employeeOrderId: 3,
              itemName: 'Mouse',
              itemId: 211,
              itemCost: 125,
              firstThreeMonthCost: 40,
            },
          ],
        },
        {
          newOrderId: 2,
          employeeName: 'Sara Jordon',
          employeeId: 25456,
          allocatedLicenceType: 'Gold',
          orderNo: 235,
          orderDate: '30/10/2020',
          orderCost: 325,
          firstThreeMonthCost: 110,
          paymentStatus: 'pending',
          orderConfirm: false,
          orderConfirmDate: '',
          dispatchStatus: false,
          dispatchDate: '',
          deliveryDate: '',
          employeeOrders: [
            {
              employeeOrderId: 1,
              itemName: 'laptop',
              itemId: 321,
              itemCost: 325,
              firstThreeMonthCost: 100,
            },
            {
              employeeOrderId: 2,
              itemName: 'Keyboard',
              itemId: 520,
              itemCost: 600,
              firstThreeMonthCost: 200,
            },
            {
              employeeOrderId: 3,
              itemName: 'Mouse',
              itemId: 211,
              itemCost: 125,
              firstThreeMonthCost: 40,
            },
          ],
        },
        {
          newOrderId: 3,
          employeeName: 'Greg wilson',
          employeeId: 25456,
          allocatedLicenceType: 'platinum',
          orderNo: 235,
          orderDate: '30/10/2020',
          orderCost: 325,
          firstThreeMonthCost: 110,
          paymentStatus: 'pending',
          orderConfirm: false,
          orderConfirmDate: '',
          dispatchStatus: false,
          dispatchDate: '',
          deliveryDate: '',
          employeeOrders: [
            {
              employeeOrderId: 1,
              itemName: 'laptop',
              itemId: 321,
              itemCost: 325,
              firstThreeMonthCost: 100,
            },
            {
              employeeOrderId: 2,
              itemName: 'Keyboard',
              itemId: 520,
              itemCost: 600,
              firstThreeMonthCost: 200,
            },
            {
              employeeOrderId: 3,
              itemName: 'Mouse',
              itemId: 211,
              itemCost: 125,
              firstThreeMonthCost: 40,
            },
          ],
        },
      ],
      pastOrder: [
        {
          pastOrderId: 1,
          employeeName: 'Mathew Jordon',
          employeeId: 25456,
          allocatedLicenceType: 'silver',
          orderNo: 235,
          orderDate: '30/11/2019',
          orderCost: 325,
          firstThreeMonthCost: 110,
          paymentStatus: 'received',
          orderConfirm: true,
          orderConfirmDate: '30/12/2019',
          dispatchStatus: true,
          dispatchDate: '01/01/2020',
          deliveryDate: '10/01/2020',
          employeeOrders: [
            {
              employeeOrderId: 1,
              itemName: 'laptop',
              itemId: 321,
              itemCost: 325,
              firstThreeMonthCost: 100,
            },
            {
              employeeOrderId: 2,
              itemName: 'Keyboard',
              itemId: 520,
              itemCost: 600,
              firstThreeMonthCost: 200,
            },
            {
              employeeOrderId: 3,
              itemName: 'Mouse',
              itemId: 211,
              itemCost: 125,
              firstThreeMonthCost: 40,
            },
          ],
        },
        {
          pastOrderId: 2,
          employeeName: 'Sara Jordon',
          employeeId: 25456,
          allocatedLicenceType: 'Gold',
          orderNo: 235,
          orderDate: '30/11/2019',
          orderCost: 325,
          firstThreeMonthCost: 110,
          paymentStatus: 'received',
          orderConfirm: true,
          orderConfirmDate: '30/12/2019',
          dispatchStatus: true,
          dispatchDate: '01/01/2020',
          deliveryDate: '10/01/2020',
          employeeOrders: [
            {
              employeeOrderId: 1,
              itemName: 'laptop',
              itemId: 321,
              itemCost: 325,
              firstThreeMonthCost: 100,
            },
            {
              employeeOrderId: 2,
              itemName: 'Keyboard',
              itemId: 520,
              itemCost: 600,
              firstThreeMonthCost: 200,
            },
            {
              employeeOrderId: 3,
              itemName: 'Mouse',
              itemId: 211,
              itemCost: 125,
              firstThreeMonthCost: 40,
            },
          ],
        },
        {
          pastOrderId: 3,
          employeeName: 'Greg wilson',
          employeeId: 25456,
          allocatedLicenceType: 'platinum',
          orderNo: 235,
          orderDate: '30/11/2019',
          orderCost: 325,
          firstThreeMonthCost: 110,
          paymentStatus: 'received',
          orderConfirm: true,
          orderConfirmDate: '30/12/2019',
          dispatchStatus: true,
          dispatchDate: '01/01/2020',
          deliveryDate: '10/01/2020',
          employeeOrders: [
            {
              employeeOrderId: 1,
              itemName: 'laptop',
              itemId: 321,
              itemCost: 325,
              firstThreeMonthCost: 100,
            },
            {
              employeeOrderId: 2,
              itemName: 'Keyboard',
              itemId: 520,
              itemCost: 600,
              firstThreeMonthCost: 200,
            },
            {
              employeeOrderId: 3,
              itemName: 'Mouse',
              itemId: 211,
              itemCost: 125,
              firstThreeMonthCost: 40,
            },
          ],
        },
      ],
    },
    {
      orderId: 4,
      corporateName: 'Corporate 4',
      contactPerson: 'velery conna',
      newOrder: [
        {
          newOrderId: 1,
          employeeName: 'Mathew Jordon',
          employeeId: 25456,
          allocatedLicenceType: 'silver',
          orderNo: 235,
          orderDate: '30/10/2020',
          orderCost: 325,
          firstThreeMonthCost: 110,
          paymentStatus: 'pending',
          orderConfirm: false,
          orderConfirmDate: '',
          dispatchStatus: false,
          dispatchDate: '',
          deliveryDate: '',
          employeeOrders: [
            {
              employeeOrderId: 1,
              itemName: 'laptop',
              itemId: 321,
              itemCost: 325,
              firstThreeMonthCost: 100,
            },
            {
              employeeOrderId: 2,
              itemName: 'Keyboard',
              itemId: 520,
              itemCost: 600,
              firstThreeMonthCost: 200,
            },
            {
              employeeOrderId: 3,
              itemName: 'Mouse',
              itemId: 211,
              itemCost: 125,
              firstThreeMonthCost: 40,
            },
          ],
        },
        {
          newOrderId: 2,
          employeeName: 'Sara Jordon',
          employeeId: 25456,
          allocatedLicenceType: 'Gold',
          orderNo: 235,
          orderDate: '30/10/2020',
          orderCost: 325,
          firstThreeMonthCost: 110,
          paymentStatus: 'pending',
          orderConfirm: false,
          orderConfirmDate: '',
          dispatchStatus: false,
          dispatchDate: '',
          deliveryDate: '',
          employeeOrders: [
            {
              employeeOrderId: 1,
              itemName: 'laptop',
              itemId: 321,
              itemCost: 325,
              firstThreeMonthCost: 100,
            },
            {
              employeeOrderId: 2,
              itemName: 'Keyboard',
              itemId: 520,
              itemCost: 600,
              firstThreeMonthCost: 200,
            },
            {
              employeeOrderId: 3,
              itemName: 'Mouse',
              itemId: 211,
              itemCost: 125,
              firstThreeMonthCost: 40,
            },
          ],
        },
        {
          newOrderId: 3,
          employeeName: 'Greg wilson',
          employeeId: 25456,
          allocatedLicenceType: 'platinum',
          orderNo: 235,
          orderDate: '30/10/2020',
          orderCost: 325,
          firstThreeMonthCost: 110,
          paymentStatus: 'pending',
          orderConfirm: false,
          orderConfirmDate: '',
          dispatchStatus: false,
          dispatchDate: '',
          deliveryDate: '',
          employeeOrders: [
            {
              employeeOrderId: 1,
              itemName: 'laptop',
              itemId: 321,
              itemCost: 325,
              firstThreeMonthCost: 100,
            },
            {
              employeeOrderId: 2,
              itemName: 'Keyboard',
              itemId: 520,
              itemCost: 600,
              firstThreeMonthCost: 200,
            },
            {
              employeeOrderId: 3,
              itemName: 'Mouse',
              itemId: 211,
              itemCost: 125,
              firstThreeMonthCost: 40,
            },
          ],
        },
      ],
      pastOrder: [
        {
          pastOrderId: 1,
          employeeName: 'Mathew Jordon',
          employeeId: 25456,
          allocatedLicenceType: 'silver',
          orderNo: 235,
          orderDate: '30/11/2019',
          orderCost: 325,
          firstThreeMonthCost: 110,
          paymentStatus: 'received',
          orderConfirm: true,
          orderConfirmDate: '30/12/2019',
          dispatchStatus: true,
          dispatchDate: '01/01/2020',
          deliveryDate: '10/01/2020',
          employeeOrders: [
            {
              employeeOrderId: 1,
              itemName: 'laptop',
              itemId: 321,
              itemCost: 325,
              firstThreeMonthCost: 100,
            },
            {
              employeeOrderId: 2,
              itemName: 'Keyboard',
              itemId: 520,
              itemCost: 600,
              firstThreeMonthCost: 200,
            },
            {
              employeeOrderId: 3,
              itemName: 'Mouse',
              itemId: 211,
              itemCost: 125,
              firstThreeMonthCost: 40,
            },
          ],
        },
        {
          pastOrderId: 2,
          employeeName: 'Sara Jordon',
          employeeId: 25456,
          allocatedLicenceType: 'Gold',
          orderNo: 235,
          orderDate: '30/11/2019',
          orderCost: 325,
          firstThreeMonthCost: 110,
          paymentStatus: 'received',
          orderConfirm: true,
          orderConfirmDate: '30/12/2019',
          dispatchStatus: true,
          dispatchDate: '01/01/2020',
          deliveryDate: '10/01/2020',
          employeeOrders: [
            {
              employeeOrderId: 1,
              itemName: 'laptop',
              itemId: 321,
              itemCost: 325,
              firstThreeMonthCost: 100,
            },
            {
              employeeOrderId: 2,
              itemName: 'Keyboard',
              itemId: 520,
              itemCost: 600,
              firstThreeMonthCost: 200,
            },
            {
              employeeOrderId: 3,
              itemName: 'Mouse',
              itemId: 211,
              itemCost: 125,
              firstThreeMonthCost: 40,
            },
          ],
        },
        {
          pastOrderId: 3,
          employeeName: 'Greg wilson',
          employeeId: 25456,
          allocatedLicenceType: 'platinum',
          orderNo: 235,
          orderDate: '30/11/2019',
          orderCost: 325,
          firstThreeMonthCost: 110,
          paymentStatus: 'received',
          orderConfirm: true,
          orderConfirmDate: '30/12/2019',
          dispatchStatus: true,
          dispatchDate: '01/01/2020',
          deliveryDate: '10/01/2020',
          employeeOrders: [
            {
              employeeOrderId: 1,
              itemName: 'laptop',
              itemId: 321,
              itemCost: 325,
              firstThreeMonthCost: 100,
            },
            {
              employeeOrderId: 2,
              itemName: 'Keyboard',
              itemId: 520,
              itemCost: 600,
              firstThreeMonthCost: 200,
            },
            {
              employeeOrderId: 3,
              itemName: 'Mouse',
              itemId: 211,
              itemCost: 125,
              firstThreeMonthCost: 40,
            },
          ],
        },
      ],
    },
    {
      orderId: 5,
      corporateName: 'Corporate 5',
      contactPerson: 'margret mat',
      newOrder: [
        {
          newOrderId: 1,
          employeeName: 'Mathew Jordon',
          employeeId: 25456,
          allocatedLicenceType: 'silver',
          orderNo: 235,
          orderDate: '30/10/2020',
          orderCost: 325,
          firstThreeMonthCost: 110,
          paymentStatus: 'pending',
          orderConfirm: false,
          orderConfirmDate: '',
          dispatchStatus: false,
          dispatchDate: '',
          deliveryDate: '',
          employeeOrders: [
            {
              employeeOrderId: 1,
              itemName: 'laptop',
              itemId: 321,
              itemCost: 325,
              firstThreeMonthCost: 100,
            },
            {
              employeeOrderId: 2,
              itemName: 'Keyboard',
              itemId: 520,
              itemCost: 600,
              firstThreeMonthCost: 200,
            },
            {
              employeeOrderId: 3,
              itemName: 'Mouse',
              itemId: 211,
              itemCost: 125,
              firstThreeMonthCost: 40,
            },
          ],
        },
        {
          newOrderId: 2,
          employeeName: 'Sara Jordon',
          employeeId: 25456,
          allocatedLicenceType: 'Gold',
          orderNo: 235,
          orderDate: '30/10/2020',
          orderCost: 325,
          firstThreeMonthCost: 110,
          paymentStatus: 'pending',
          orderConfirm: false,
          orderConfirmDate: '',
          dispatchStatus: false,
          dispatchDate: '',
          deliveryDate: '',
          employeeOrders: [
            {
              employeeOrderId: 1,
              itemName: 'laptop',
              itemId: 321,
              itemCost: 325,
              firstThreeMonthCost: 100,
            },
            {
              employeeOrderId: 2,
              itemName: 'Keyboard',
              itemId: 520,
              itemCost: 600,
              firstThreeMonthCost: 200,
            },
            {
              employeeOrderId: 3,
              itemName: 'Mouse',
              itemId: 211,
              itemCost: 125,
              firstThreeMonthCost: 40,
            },
          ],
        },
        {
          newOrderId: 3,
          employeeName: 'Greg wilson',
          employeeId: 25456,
          allocatedLicenceType: 'platinum',
          orderNo: 235,
          orderDate: '30/10/2020',
          orderCost: 325,
          firstThreeMonthCost: 110,
          paymentStatus: 'pending',
          orderConfirm: false,
          orderConfirmDate: '',
          dispatchStatus: false,
          dispatchDate: '',
          deliveryDate: '',
          employeeOrders: [
            {
              employeeOrderId: 1,
              itemName: 'laptop',
              itemId: 321,
              itemCost: 325,
              firstThreeMonthCost: 100,
            },
            {
              employeeOrderId: 2,
              itemName: 'Keyboard',
              itemId: 520,
              itemCost: 600,
              firstThreeMonthCost: 200,
            },
            {
              employeeOrderId: 3,
              itemName: 'Mouse',
              itemId: 211,
              itemCost: 125,
              firstThreeMonthCost: 40,
            },
          ],
        },
      ],
      pastOrder: [
        {
          pastOrderId: 1,
          employeeName: 'Mathew Jordon',
          employeeId: 25456,
          allocatedLicenceType: 'silver',
          orderNo: 235,
          orderDate: '30/11/2019',
          orderCost: 325,
          firstThreeMonthCost: 110,
          paymentStatus: 'received',
          orderConfirm: true,
          orderConfirmDate: '30/12/2019',
          dispatchStatus: true,
          dispatchDate: '01/01/2020',
          deliveryDate: '10/01/2020',
          employeeOrders: [
            {
              employeeOrderId: 1,
              itemName: 'laptop',
              itemId: 321,
              itemCost: 325,
              firstThreeMonthCost: 100,
            },
            {
              employeeOrderId: 2,
              itemName: 'Keyboard',
              itemId: 520,
              itemCost: 600,
              firstThreeMonthCost: 200,
            },
            {
              employeeOrderId: 3,
              itemName: 'Mouse',
              itemId: 211,
              itemCost: 125,
              firstThreeMonthCost: 40,
            },
          ],
        },
        {
          pastOrderId: 2,
          employeeName: 'Sara Jordon',
          employeeId: 25456,
          allocatedLicenceType: 'Gold',
          orderNo: 235,
          orderDate: '30/11/2019',
          orderCost: 325,
          firstThreeMonthCost: 110,
          paymentStatus: 'received',
          orderConfirm: true,
          orderConfirmDate: '30/12/2019',
          dispatchStatus: true,
          dispatchDate: '01/01/2020',
          deliveryDate: '10/01/2020',
          employeeOrders: [
            {
              employeeOrderId: 1,
              itemName: 'laptop',
              itemId: 321,
              itemCost: 325,
              firstThreeMonthCost: 100,
            },
            {
              employeeOrderId: 2,
              itemName: 'Keyboard',
              itemId: 520,
              itemCost: 600,
              firstThreeMonthCost: 200,
            },
            {
              employeeOrderId: 3,
              itemName: 'Mouse',
              itemId: 211,
              itemCost: 125,
              firstThreeMonthCost: 40,
            },
          ],
        },
        {
          pastOrderId: 3,
          employeeName: 'Greg wilson',
          employeeId: 25456,
          allocatedLicenceType: 'platinum',
          orderNo: 235,
          orderDate: '30/11/2019',
          orderCost: 325,
          firstThreeMonthCost: 110,
          paymentStatus: 'received',
          orderConfirm: true,
          orderConfirmDate: '30/12/2019',
          dispatchStatus: true,
          dispatchDate: '01/01/2020',
          deliveryDate: '10/01/2020',
          employeeOrders: [
            {
              employeeOrderId: 1,
              itemName: 'laptop',
              itemId: 321,
              itemCost: 325,
              firstThreeMonthCost: 100,
            },
            {
              employeeOrderId: 2,
              itemName: 'Keyboard',
              itemId: 520,
              itemCost: 600,
              firstThreeMonthCost: 200,
            },
            {
              employeeOrderId: 3,
              itemName: 'Mouse',
              itemId: 211,
              itemCost: 125,
              firstThreeMonthCost: 40,
            },
          ],
        },
      ],
    },
  ],
};

const manageOrderReducer = (state = initialState, action) => {
  switch (action.type) {
    case manageOrderMap.UPDATE_MANAGE_ORDER_NEW_ORDER_CONFIRM: {
      let tempManageOrderData = state.manageOrderData.map((order) => {
        if (order.orderId === action.payload.orderId) {
          let tempNewOrder = order.newOrder.map((singleNewOrder) => {
            if (singleNewOrder.newOrderId === action.payload.newOrderId) {
              return {
                ...singleNewOrder,
                orderConfirm: action.payload.orderConfirm,
                orderConfirmDate: action.payload.orderConfirmDate,
              };
            } else {
              return singleNewOrder;
            }
          });
          return { ...order, newOrder: tempNewOrder };
        } else {
          return order;
        }
      });
      return {
        ...state,
        manageOrderData: tempManageOrderData,
      };
    }
    case manageOrderMap.UPDATE_MANAGE_ORDER_NEW_ORDER_DISPATCH_DETAILS: {
      let tempManageOrderData = state.manageOrderData.map((order) => {
        if (order.orderId === action.payload.orderId) {
          let tempNewOrder = order.newOrder.map((singleNewOrder) => {
            if (singleNewOrder.newOrderId === action.payload.newOrderId) {
              return {
                ...singleNewOrder,
                dispatchStatus: action.payload.dispatchStatus,
                dispatchDate: action.payload.dispatchDate,
                deliveryDate: action.payload.deliveryDate,
              };
            } else {
              return singleNewOrder;
            }
          });
          return { ...order, newOrder: tempNewOrder };
        } else {
          return order;
        }
      });
      return {
        ...state,
        manageOrderData: tempManageOrderData,
      };
    }
    default:
      return state;
  }
};

export default manageOrderReducer;
